GuardiaoBrindes_Config = {
	WindowID = 150,

	Packet = 0x34,

	Description = true,

	Texts = {
		["Eng"] = {
			[1] = "Guardião dos Brindes",
			[2] = "Olá, eu sou o Guardião de Brindes!",
			[3] = "Sempre que você receber um brinde",
			[4] = "ou prêmio via código, eu os guardarei",
			[5] = "até que você possa retirá-los comigo.",
			[6] = "Para retirar, basta que você me",
			[7] = "informe seu Código de Acesso:",
			[8] = "Acessar Código",
			[9] = "Meus Brindes",
			[11] = "Selecione um brinde na lista abaixo",
			[12] = "Acessar",
			[13] = "Código de Acesso",
			[14] = "Validade do Código",
			[15] = "Retirar",
			[16] = "Selecione um item na lista abaixo",
			[17] = "Seu item foi retirado com sucesso!",
			[18] = "Esse item não está mais disponível",
			[19] = "Código de Acesso inválido",
			[20] = "Nenhum item disponível para",
			[21] = "o código de acesso informado",
			[22] = "Não há mais itens a serem retirados",
			[23] = "Você não possuí brindes a serem retirados",
			[24] = "Não há espaço para o item no iventário",
		},

		["Por"] = {
			[1] = "Guardião dos Brindes",
			[2] = "Olá, eu sou o Guardião de Brindes!",
			[3] = "Sempre que você receber um brinde",
			[4] = "ou prêmio via código, eu os guardarei",
			[5] = "até que você possa retirá-los comigo.",
			[6] = "Para retirar, basta que você me",
			[7] = "informe seu Código de Acesso:",
			[8] = "Acessar Código",
			[9] = "Meus Brindes",
			[11] = "Selecione um brinde na lista abaixo",
			[12] = "Acessar",
			[13] = "Código de Acesso",
			[14] = "Validade do Código",
			[15] = "Retirar",
			[16] = "Selecione um item na lista abaixo",
			[17] = "Seu item foi retirado com sucesso!",
			[18] = "Esse item não está mais disponível",
			[19] = "Código de Acesso inválido",
			[20] = "Nenhum item disponível para",
			[21] = "o código de acesso informado",
			[22] = "Não há mais itens a serem retirados",
			[23] = "Você não possuí brindes a serem retirados",
			[24] = "Não há espaço para o item no iventário",
		},

		["Spn"] = {
			[1] = "Guardião dos Brindes",
			[2] = "Olá, eu sou o Guardião de Brindes!",
			[3] = "Sempre que você receber um brinde",
			[4] = "ou prêmio via código, eu os guardarei",
			[5] = "até que você possa retirá-los comigo.",
			[6] = "Para retirar, basta que você me",
			[7] = "informe seu Código de Acesso:",
			[8] = "Acessar Código",
			[9] = "Meus Brindes",
			[11] = "Selecione um brinde na lista abaixo",
			[12] = "Acessar",
			[13] = "Código de Acesso",
			[14] = "Validade do Código",
			[15] = "Retirar",
			[16] = "Selecione um item na lista abaixo",
			[17] = "Seu item foi retirado com sucesso!",
			[18] = "Esse item não está mais disponível",
			[19] = "Código de Acesso inválido",
			[20] = "Nenhum item disponível para",
			[21] = "o código de acesso informado",
			[22] = "Não há mais itens a serem retirados",
			[23] = "Você não possuí brindes a serem retirados",
			[24] = "Não há espaço para o item no iventário",
		}
	}
}