<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Condition="'$(MSBuildProjectName)'=='Main'">
    <ClCompile Include="$(MSBuildProjectDirectory)\source\Render\Model\BMDModernMesh.cpp" />
    <ClCompile Include="$(MSBuildProjectDirectory)\source\Render\Model\SkeletonBuffer.cpp" />
    <ClCompile Include="$(MSBuildProjectDirectory)\source\Render\Model\SkeletonEncoder.cpp" />
    <ClCompile Include="$(MSBuildProjectDirectory)\source\Render\Model\SkeletonEncoderTests.cpp" />
    <ClCompile Include="$(MSBuildProjectDirectory)\source\Render\OpenGL\OpenGLBMDModernBindings.cpp" />
    <ClCompile Include="$(MSBuildProjectDirectory)\source\Render\OpenGL\OpenGLBMDModernInstanceBuffer.cpp" />
    <ClCompile Include="$(MSBuildProjectDirectory)\source\Render\OpenGL\OpenGLBMDModernVAO.cpp" />
    <ClCompile Include="$(MSBuildProjectDirectory)\source\Render\OpenGL\OpenGLShaderGlobalConstants.cpp" />
    <ClCompile Include="$(MSBuildProjectDirectory)\source\Render\OpenGL\OpenGLSkeletonTexture.cpp" />
  </ItemGroup>
</Project>
