#include "stdafx.h"
#include "MuHelperProtocol.h"
#include "CAIController.h"
#include "NewUISystem.h"
#include "wsclientinline.h"

void BindMuHelperCharacter(CHARACTER* character)
{
	// HeroIndex is randomized on every map join in MuBattle. Rebinding prevents
	// the Helper loop from retaining the previous map's CHARACTER pointer.
	gmAIController->SetActiveCharacter(character);
}

void SendRequestStartHelper(BYTE status)
{
	CStreamPacketEngine packet;
	packet.Init(0xC1, 0xBF);
	packet << (BYTE)0x51;
	packet << status;
	packet.Send();
}

void SendRequestSaveHelperSetting(BYTE* buffer, int size)
{
	if (buffer == NULL || size != 256)
	{
		return;
	}

	CStreamPacketEngine packet;
	packet.Init(0xC2, 0xAE);
	packet << (BYTE)0;
	packet.AddData(buffer, size);
	packet.Send();
}

void ReceiveMuHelperData(BYTE* buffer)
{
	if (buffer == NULL || gProtect->m_MainInfo.m_MuHelperEnabled == 0)
	{
		return;
	}

	// C2 header layout: type, size-high, size-low, head, result, data[256].
	gmAIController->ResetConfig();
	if (buffer[4] == 0)
	{
		gmAIController->Unpack(&buffer[5]);
	}
}

void ReceiveMuHelperResult(BYTE* buffer)
{
	if (buffer == NULL || gProtect->m_MainInfo.m_MuHelperEnabled == 0)
	{
		return;
	}

	// C1 BF:51 layout generated by PMSG_HELPER_START_SEND in Helper.h.
	const DWORD elapsedMinutes = *(DWORD*)&buffer[4];
	const DWORD money = *(DWORD*)&buffer[8];
	const BYTE result = buffer[12];

	if (result == 0)
	{
		if (elapsedMinutes != 0)
		{
			unicode::t_char text[256] = { 0 };
			unicode::_sprintf(text, GlobalText[3586], money);
			g_pChatListBox->AddText("", text, SEASON3B::TYPE_ERROR_MESSAGE);
			if (g_pMacroGaugeBar != NULL)
			{
				g_pMacroGaugeBar->SetMacroExpense((int)money);
			}
		}
		else
		{
			gmAIController->Start();
			g_pChatListBox->AddText("", GlobalText[3562], SEASON3B::TYPE_SYSTEM_MESSAGE);
		}
	}
	else if (result == 1)
	{
		gmAIController->Stop();
	}
	else if (result == 2)
	{
		g_pChatListBox->AddText("", GlobalText[3587], SEASON3B::TYPE_ERROR_MESSAGE);
		SendRequestStartHelper(TRUE);
	}
}
