[MainInfo]
;=================================================================================
; CustomerName: Seu Customername (deve ser igual do Common.dat)
; IpAddress: IP da sua VPS (ou dominio de redirecionamento cloudflare)
; IpAddressPort: Porta do seu ConnectServer
; HackServerPort: Porta do HackServers
; UseIntegratedAntiHack: Usar Sistema de AntiHack intergrado
; ClientVersion: Versão do Client (deve ser igual do Common.dar e HackServer
; ClientSerial: Deve ser igual do Common.dat e do HackServer (não use o padrão)
;		 ao troca-lo, você deve encriptar novamente todos os Scripts.
; WindowName: Nome que irá aparecer na janela do Jogo
; ScreenShotPath: Nao altere
; DebugConsole: Ativa o Console de Debug do cliente
; OpenLauncher: Forca abrir o jogo pelo Launcher
;		(so habilite esta opção de estiver usando Launcher Externo)
; LauncherName = Nome do Executavel do Launcher
; MaxInstance = Maximo de janelas abertas em simuntâneo (BETA)
; RequireAdmin = Força execução do Jogo como Administrador
; RequireAdminMessage = Exibe mensagem de confirmação de Administrador
; BlockVirtualMachine = Bloqueio de Maquinas Virtuais
;=================================================================================
CustomerName			= muonline
IpAddress 			= 172.23.208.1
IpAddressPort 			= 44405
MHPServerPort			= 55999
UseIntegratedAntiHack		= 0
ClientVersion 			= 1.04.05
ClientSerial 			= TbYehR2hFUPBKgZj
WindowName 			= MuOnline
ScreenShotPath 			= ScreenShots\Screen(%02d_%02d-%02d-%02d)-%04d.jpg
OpenLauncher 			= 0
LauncherName 			= Launcher.exe
DebugConsole 			= 0
MaxInstance 			= 20
RequireAdmin 			= 1
RequireAdminMessage 		= 0
BlockVirtualMachine 		= 1

[HelperInfo]
MuHelperEnabled        = 1
HelperActiveAlert      = 0
HelperActiveLevel      = 80

[IntegratedLauncher]
;=================================================================================
; Para usar estas Opções, desative: OpenLauncher acima!
; AutoUpdateCpanel = Main.exe puxar atualizações do direto do cPanel
; AutoUpdateURL = URL de Update do cPanel (mantenha https:// e termine com / )
; As cores da tela de atualizacao sao definidas no arquivo UpdateColors.txt
; MaxUpdateTips: Maximo de Dicas na tela de Update Configure em UpdateColors.txt
;=================================================================================
AutoUpdateCpanel 		= 0
AutoUpdateURL 			= https://update.seulinkdeupdatecpanel.com/
TitleName 			= SEU SERVIDOR SEASON 4
SubTitleName 			= OPEN GL 3 - 120 FPS
WebSiteURL 			= seusite.com
MaxUpdateTips 			= 7

[PluginSystem]
;=================================================================================
; AntiBypassDLL: Ative somente se estiver usando DLLs
; PluginName1 a 5: Dlls de AntiHackers externos (desative UseIntegratedAntiHack)
;=================================================================================
AntiBypassDLL 			= 0
PluginName1 			=
PluginName2 			=
PluginName3 			=
PluginName4 			=
PluginName5 			=

[LuaSystemClient]
;=================================================================================
; ReloadLua: Recarregar o Lua do Cliente InGame (tecla HOME)
; OnlyCryptedLua: Permite o jogo abrir somente se os scripts tiver encriptados
; PrivateCode: Codigo de criptografia dos scripts Lua
;=================================================================================
ReloadLua 			= 0
OnlyCryptedLua 			= 1
PrivateCode 			= X9kPqW2vT7rZ4cL8mB5jYfN3sH6tA1u

[SystemRequirements]
;=================================================================================
; CheckRequeriments = Habilita a Verificação de sistema
; CheckWindowsVersion = Versão do Windows (7, 8, 10, 11)
; MinMemoryRAMCheck   = Minimo de memoria RAM
; MinCPUCoreCheck     = Minimo de Núcleos do Processador
; MinVideoMemory     = Minimo de VRAM da Placa de Vídeo
;=================================================================================
CheckRequeriments 		= 1
CheckWindowsVersion 		= 10
MinMemoryRAMCheck 		= 4
MinCPUCoreCheck 		= 4
MinVideoMemory	 		= 0

[Interface]
;=================================================================================
; WidesCreenType
; 	0 = Mantem Interface travada no do 1366x768
; 	1 = Reduz Interface conforme Resolução Aumenta (BETA)
; DisableClassSUM: Desabilita criação de Summoner
; VideoLogin: Tela de Login em Vídeo MP4 (Client/Data/Custom/Movie)
; VisualBugHPFerrarezi: Simulação de Bug de HP Leo Ferrarezi
; SelectServerCustom: Para usar SelectServer sem Tour de Camera (parado)
;=================================================================================
WidesCreenType			= 1
DisableClassSUM		 	= 0
VideoLogin		 	= 0
VisualBugHPFerrarezi		= 0
SelectServerCustom		= 0

[Custom]
;=================================================================================
; LoadingLegend: Habilita Tela de Carregamento MuLegends
; LoadingImageCount: Quantidade de Imagens de Loading (Max 15)
; GMGiftPlayerTrade: Permite Players passar Box de GM no Trade
; TCAAllowTrade: Permite Players passar Talismã Chaos Assembli no Trade
; LuckyTalismanAllowTrade: Permite Players passar Talismã of Lucky no Trade
; SkillDisableEffect: Desabilita efeito da Slash, Decay, Ice e Birds
; ShowFPSWindow: Mostra FPS na Janela do Jogo
; BlockSellTemporayNPC: Bloqueia venda de Itens temporarios no NPC
; MountMiniSafeZone: Montaris em Miniaturas na SafeZone
; TooltipAnimation: Animação nos Tooltips dos Itens
; NoDelayPotion: Sistema de Nodelay nas porções
;=================================================================================
LoadingLegend 			= 1
LoadingImageCount 		= 1
GMGiftPlayerTrade 		= 0
TCAAllowTrade 			= 0
LuckyTalismanAllowTrade 	= 0
SkillDisableEffect 		= 0
ShowFPSWindow	 		= 1
BlockSellTemporayNPC 		= 0
MountMiniSafeZone		= 0
TooltipAnimation		= 0
NoDelayPotion			= 0

[HardwareID]
;=================================================================================
; GetHWID: 1 = Obter HardwareID do Player
; ShowHWID: 1 = Exibe o HWID na janela do Jogo
; BlockHWID: HWID Bloqueados separados por vírgulas
; Ex: 55D3B74A-92FFC6EA-F25CA223-8D28B7EF,55D3B74A-92FFC6EA-F25CA223-8D28B7EF...
;=================================================================================
GetHWID 			= 0
ShowHWID 			= 0
BlockHWID 			=
